spring.application.name=logisticms
server.port=8080
spring.profiles.active=dev

spring.datasource.url=jdbc:postgresql://localhost:5432/logistic_db
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

internal.token=${INTERNAL_MS_TOKEN}
loginms.url=${LOGIN_MS_URL}

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000