# ------------------------------
# Database Configuration (Postgres)
# ------------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

spring.datasource.hikari.pool-name=HikariPool
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
